export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';

export const SHOW_HOME_RECOS_LOADER = 'SHOW_HOME_RECOS_LOADER';
export const HIDE_HOME_RECOS_LOADER = 'HIDE_HOME_RECOS_LOADER';

export const POST_CONSUMER_PROFILE_SUCCESS = 'POST_CONSUMER_PROFILE_SUCCESS';
export const POST_CONSUMER_PROFILE_FAILURE = 'POST_CONSUMER_PROFILE_FAILURE';

export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS';
export const POST_LOGIN_FAILURE = 'POST_LOGIN_FAILURE';